### ISSUE TITLE
Customizing Icon

### ISSUE THREAD

**Issue by lua-latex** [justas-d/mpd-rich-presence-discord#16]
I've replaced the `mpd.svg` file with an svg of my own (one that I would like to use instead of the default icon) and ran the `makePng.sh` script to generate a raster image of it in the `assets/discord/png` folder. 

However, when I recompile the project and run `mpd_discord_richpresence`, the image remains as it was previously.

Looking through all the source files I can't seem to find anything pertaining to the `mpd.svg|png` file either, is the icon hardcoded into the binary?

If so how would I go about changing it?

**Comment by lua-latex** [comment]
![image](https://user-images.githubusercontent.com/85648476/122245857-b48f5380-ce8b-11eb-8eb6-a83ecc91967a.png)

Tried to take a peek at the binary itself, it mentions an `mpd_large` object, which I assume is the icon in use. There is also a reference to it in `main.cpp`.

**Comment by lua-latex** [comment]
Replacing `mpd_large` with just `mpd` seems to break the program, so I doubt it's referencing a filename like the other variables.

e.g:

![image](https://user-images.githubusercontent.com/85648476/122246354-18198100-ce8c-11eb-9d67-6bbb913d501e.png)

**Comment by justas-d** [comment]
The image is controlled by the discord "app". See: 
![image](https://user-images.githubusercontent.com/10726335/122611434-00a7e700-d08a-11eb-857d-d370b65543ac.png)

You'd have to change the app ids here to your custom ones https://github.com/justas-d/mpd-rich-presence-discord/blob/master/src/main.cpp#L14

**Comment by lua-latex** [comment]
![image](https://user-images.githubusercontent.com/85648476/122614183-c7508680-d04b-11eb-84a2-f28f5c3b3c43.png)

lmao got it.

thanks so much for the help!
